#version: '3.9'

services:
  joal_measurements:
    container_name: joal_measurements
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
      - static_volume:/data/web/static/
      - media_volume:/data/web/media/
    env_file:
      - ./.env.prod
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  frontend-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.${APP_ENV}.conf:/etc/nginx/nginx.conf:ro"
      - static_volume:/data/web/static/
      - media_volume:/data/web/media/
    depends_on:
      - joal_measurements
    environment:
      - APP_ENV=${APP_ENV}

volumes:
  static_volume:
  media_volume:
  postgres_data: