#version: '3.9'

services:
  joal_measurements:
    container_name: joal_measurements
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
      - static_volume:/data/web/static/
      - media_volume:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

volumes:
  static_volume:
  media_volume:
  postgres_data: