# Generated by Django 5.2.6 on 2025-10-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurementmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MeasurementsGroup',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
