# Generated by Django 5.2.6 on 2025-09-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurementsgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementsgroup',
            options={'verbose_name': 'Measurement Group', 'verbose_name_plural': 'Measurement Groups'},
        ),
    ]
