# Generated by Django 5.2.6 on 2025-09-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_alter_measurementsgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounts_detail', models.TextField(blank=True, null=True)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('InProgress', 'Em andamento (Engenheiro)'), ('PendingManagerApproval', 'Pendente aprovação Gerente'), ('PendingDirectorApproval', 'Pendente aprovação Diretor'), ('Finished', 'Liberado')], default='InProgress', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
